CREATE TABLE IF NOT EXISTS `quotes` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `quote` text NOT NULL,
  `author` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
INSERT INTO quotes(quote, author)
VALUES
("Life is temporary, chai break is permanent.", "Mallu Brainrot"),
("When WiFi is slow, even the coconut trees judge you.", "Kerala Logic"),
("Dream big but wake up early because KSRTC waits for no one.", "Bus Stop Philosopher"),
("My brain says study, my heart says tea kada.", "Engineering Mallu"),
("Rain in Kerala is not weather, it is lifestyle.", "Monsoon Uncle"),
("Calories do not count if eaten with sambar.", "Fitness Mallu"),
("Confidence level is wearing chappal to wedding.", "Bold Mallu"),
("Success is reaching home before heavy rain.", "Achievement Unlocked"),
("Kerala roads teach patience for free.", "Driving School"),
("I run on chai not motivation.", "Daily Routine"),
("Logic disappears when exam hall appears.", "Student Mallu"),
("My talent is finding shade anywhere.", "Survival Pro"),
("Rain makes everyone philosopher.", "Weather Thinker"),
("If plan fails add extra curry.", "Problem Solver"),
("Peace is sitting near window during rain.", "Simple Joys"),
("Even mosquitoes are athletic here.", "Night Sufferer"),
("Life advice sounds louder in Malayalam.", "Language Lover"),
("I trust bakery uncle with my life choices.", "Snack Dealer"),
("Monday hits harder than monsoon rain.", "Office Mallu"),
("Hunger increases after saying not hungry.", "Science Mallu"),
("Kerala time is flexible like banana leaf.", "Time Manager"),
("Success smells like fresh tea powder.", "Dreamer"),
("My brain is on power saving mode.", "Low Battery"),
("Success is reaching home before heavy rain.", "Achievement Unlocked"),
("Kerala roads teach patience for free.", "Driving School"),
("I run on chai not motivation.", "Daily Routine"),
("Logic disappears when exam hall appears.", "Student Mallu"),
("My talent is finding shade anywhere.", "Survival Pro"),
("Rain makes everyone philosopher.", "Weather Thinker"),
("If plan fails add extra curry.", "Problem Solver"),
("Peace is sitting near window during rain.", "Simple Joys"),
("Even mosquitoes are athletic here.", "Night Sufferer"),
("Life advice sounds louder in Malayalam.", "Language Lover"),
("I trust bakery uncle with my life choices.", "Snack Dealer"),
("Monday hits harder than monsoon rain.", "Office Mallu"),
("Hunger increases after saying not hungry.", "Science Mallu"),
("Kerala time is flexible like banana leaf.", "Time Manager"),
("Success smells like fresh tea powder.", "Dreamer"),
("My brain is on power saving mode.", "Low Battery"),
("Success is reaching home before heavy rain.", "Achievement Unlocked"),
("Kerala roads teach patience for free.", "Driving School"),
("I run on chai not motivation.", "Daily Routine"),
("Logic disappears when exam hall appears.", "Student Mallu"),
("My talent is finding shade anywhere.", "Survival Pro"),
("Rain makes everyone philosopher.", "Weather Thinker"),
("If plan fails add extra curry.", "Problem Solver"),
("Peace is sitting near window during rain.", "Simple Joys"),
("Even mosquitoes are athletic here.", "Night Sufferer"),
("Life advice sounds louder in Malayalam.", "Language Lover"),
("I trust bakery uncle with my life choices.", "Snack Dealer"),
("Monday hits harder than monsoon rain.", "Office Mallu"),
("Hunger increases after saying not hungry.", "Science Mallu"),
("Kerala time is flexible like banana leaf.", "Time Manager"),
("Success smells like fresh tea powder.", "Dreamer"),
("My brain is on power saving mode.", "Low Battery"),
("Success is reaching home before heavy rain.", "Achievement Unlocked"),
("Kerala roads teach patience for free.", "Driving School"),
("I run on chai not motivation.", "Daily Routine"),
("Logic disappears when exam hall appears.", "Student Mallu"),
("My talent is finding shade anywhere.", "Survival Pro"),
("Rain makes everyone philosopher.", "Weather Thinker"),
("If plan fails add extra curry.", "Problem Solver"),
("Peace is sitting near window during rain.", "Simple Joys"),
("Even mosquitoes are athletic here.", "Night Sufferer"),
("Life advice sounds louder in Malayalam.", "Language Lover"),
("I trust bakery uncle with my life choices.", "Snack Dealer"),
("Monday hits harder than monsoon rain.", "Office Mallu"),
("Hunger increases after saying not hungry.", "Science Mallu"),
("Kerala time is flexible like banana leaf.", "Time Manager"),
("Success smells like fresh tea powder.", "Dreamer"),
("My brain is on power saving mode.", "Low Battery"),
("Success is reaching home before heavy rain.", "Achievement Unlocked"),
("Kerala roads teach patience for free.", "Driving School"),
("I run on chai not motivation.", "Daily Routine"),
("Logic disappears when exam hall appears.", "Student Mallu"),
("My talent is finding shade anywhere.", "Survival Pro"),
("Rain makes everyone philosopher.", "Weather Thinker"),
("If plan fails add extra curry.", "Problem Solver"),
("Peace is sitting near window during rain.", "Simple Joys"),
("Even mosquitoes are athletic here.", "Night Sufferer"),
("Life advice sounds louder in Malayalam.", "Language Lover"),
("I trust bakery uncle with my life choices.", "Snack Dealer"),
("Monday hits harder than monsoon rain.", "Office Mallu"),
("Hunger increases after saying not hungry.", "Science Mallu"),
("Kerala time is flexible like banana leaf.", "Time Manager"),
("Success smells like fresh tea powder.", "Dreamer"),
("My brain is on power saving mode.", "Low Battery"),
("Success is reaching home before heavy rain.", "Achievement Unlocked"),
("Kerala roads teach patience for free.", "Driving School"),
("I run on chai not motivation.", "Daily Routine"),
("Logic disappears when exam hall appears.", "Student Mallu"),
("My talent is finding shade anywhere.", "Survival Pro"),
("Rain makes everyone philosopher.", "Weather Thinker"),
("If plan fails add extra curry.", "Problem Solver"),
("Peace is sitting near window during rain.", "Simple Joys"),
("Even mosquitoes are athletic here.", "Night Sufferer"),
("Life advice sounds louder in Malayalam.", "Language Lover"),
("I trust bakery uncle with my life choices.", "Snack Dealer"),
("Monday hits harder than monsoon rain.", "Office Mallu"),
("Hunger increases after saying not hungry.", "Science Mallu"),
("Kerala time is flexible like banana leaf.", "Time Manager"),
("Success smells like fresh tea powder.", "Dreamer"),
("My brain is on power saving mode.", "Low Battery"),
("Success is reaching home before heavy rain.", "Achievement Unlocked"),
("Kerala roads teach patience for free.", "Driving School"),
("I run on chai not motivation.", "Daily Routine"),
("Logic disappears when exam hall appears.", "Student Mallu"),
("My talent is finding shade anywhere.", "Survival Pro"),
("Rain makes everyone philosopher.", "Weather Thinker"),
("If plan fails add extra curry.", "Problem Solver"),
("Peace is sitting near window during rain.", "Simple Joys"),
("Even mosquitoes are athletic here.", "Night Sufferer"),
("Life advice sounds louder in Malayalam.", "Language Lover"),
("I trust bakery uncle with my life choices.", "Snack Dealer"),
("Monday hits harder than monsoon rain.", "Office Mallu"),
("Hunger increases after saying not hungry.", "Science Mallu"),
("Kerala time is flexible like banana leaf.", "Time Manager"),
("Success smells like fresh tea powder.", "Dreamer"),
("My brain is on power saving mode.", "Low Battery"),
("I do not need therapy, I need puttu and kadala.", "Breakfast Expert"),
("Autokaaran knows your destination before you do.", "Auto Chettan"),
("Life advice sounds better when Amma says it twice.", "Universal Truth"),
("Brain loading failed please insert pazham.", "System Mallu"),
("Even Google Maps fears Kerala shortcuts.", "Tech Mallu"),
("I came, I saw, I took a power nap.", "Lazy Legend"),
("Hard work pays off but afternoon sleep pays instantly.", "Sleep Scientist"),
("If lost, follow the smell of dosa.", "Survival Guide"),
("My mood changes faster than Kerala weather.", "Mood Swing Mallu"),
("Education is important but snacks are importanter.", "Tuition Bench"),
("Silence is golden unless relatives visit.", "Family Survivor"),
("Life goal is front seat in bus.", "Peak Happiness"),
("Motivation lasts till the kettle whistles.", "Tea Addict"),
("I trust Amma more than Google reviews.", "Wise Child"),
("Rain + current cut = free meditation.", "Zen Mallu"),
("Overthinking powered by evening chai.", "Mental Gym"),
("My schedule depends on power cut timing.", "Electricity Expert"),
("Weekend plan is doing nothing professionally.", "Certified Chill"),
("Stress level reduces after one banana fry.", "Health Guru"),
("Life lesson learned from queue at bakery.", "Snack Economist"),
("Happiness is extra pickle on the side.", "Food Poet"),
("I measure distance in minutes not kilometers.", "Local Traveller"),
("Brain says no but mouth says one more bite.", "Honest Human"),
("Success is reaching home before heavy rain.", "Achievement Unlocked"),
("Kerala roads teach patience for free.", "Driving School"),
("I run on chai not motivation.", "Daily Routine"),
("Logic disappears when exam hall appears.", "Student Mallu"),
("My talent is finding shade anywhere.", "Survival Pro"),
("Rain makes everyone philosopher.", "Weather Thinker"),
("If plan fails add extra curry.", "Problem Solver"),
("Peace is sitting near window during rain.", "Simple Joys"),
("Even mosquitoes are athletic here.", "Night Sufferer"),
("Life advice sounds louder in Malayalam.", "Language Lover"),
("I trust bakery uncle with my life choices.", "Snack Dealer"),
("Monday hits harder than monsoon rain.", "Office Mallu"),
("Hunger increases after saying not hungry.", "Science Mallu"),
("Kerala time is flexible like banana leaf.", "Time Manager"),
("Success smells like fresh tea powder.", "Dreamer"),
("My brain is on power saving mode.", "Low Battery"),
("Success is reaching home before heavy rain.", "Achievement Unlocked"),
("Kerala roads teach patience for free.", "Driving School"),
("I run on chai not motivation.", "Daily Routine"),
("Logic disappears when exam hall appears.", "Student Mallu"),
("My talent is finding shade anywhere.", "Survival Pro"),
("Rain makes everyone philosopher.", "Weather Thinker"),
("If plan fails add extra curry.", "Problem Solver"),
("Peace is sitting near window during rain.", "Simple Joys"),
("Even mosquitoes are athletic here.", "Night Sufferer"),
("Life advice sounds louder in Malayalam.", "Language Lover"),
("I trust bakery uncle with my life choices.", "Snack Dealer"),
("Monday hits harder than monsoon rain.", "Office Mallu"),
("Hunger increases after saying not hungry.", "Science Mallu"),
("Kerala time is flexible like banana leaf.", "Time Manager"),
("Success smells like fresh tea powder.", "Dreamer"),
("My brain is on power saving mode.", "Low Battery"),
("Success is reaching home before heavy rain.", "Achievement Unlocked"),
("Kerala roads teach patience for free.", "Driving School"),
("I run on chai not motivation.", "Daily Routine"),
("Logic disappears when exam hall appears.", "Student Mallu"),
("My talent is finding shade anywhere.", "Survival Pro"),
("Rain makes everyone philosopher.", "Weather Thinker"),
("If plan fails add extra curry.", "Problem Solver"),
("Peace is sitting near window during rain.", "Simple Joys"),
("Even mosquitoes are athletic here.", "Night Sufferer"),
("Life advice sounds louder in Malayalam.", "Language Lover"),
("I trust bakery uncle with my life choices.", "Snack Dealer"),
("Monday hits harder than monsoon rain.", "Office Mallu"),
("Hunger increases after saying not hungry.", "Science Mallu"),
("Kerala time is flexible like banana leaf.", "Time Manager"),
("Success smells like fresh tea powder.", "Dreamer"),
("My brain is on power saving mode.", "Low Battery"),
("In doubt add more coconut.", "Recipe Expert"),
("I do multitasking by worrying about everything.", "Professional Worrier");
