apiVersion: k3d.io/v1alpha4
kind: Simple
metadata:
  name: aura
servers: 1
agents: 3
ports:
  - port: 30090:30090 # Prometheus
    nodeFilters:
      - loadbalancer
  - port: 32322:32322 # Grafana
    nodeFilters:
      - loadbalancer
  - port: 30089:30089 # Locust
options:
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:0
  runtime:
    gpuRequest: ""
    serversMemory: "8192M"
    agentsMemory: "6144M"
