apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: envoy-metrics
  namespace: monitoring
spec:
  selector:
    matchLabels:
      metrics: envoy
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: metrics
      path: /stats/prometheus
      interval: 15s
