apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
        metrics: envoy
    spec:
      containers:
      - name: app
        image: project-app:local
        imagePullPolicy: IfNotPresent
        env:
          - name: API_URL
            value: "http://localhost:8080"
        ports:
          - containerPort: 5002

      - name: envoy
        image: envoyproxy/envoy:v1.29-latest
        command:
          - /bin/sh
          - -c
          - |
            sleep 5
            exec /usr/local/bin/envoy \
              -c /etc/envoy/envoy.yaml \
              --service-cluster app \
              --log-level info
        ports:
          - containerPort: 8080
          - containerPort: 9901
        volumeMounts:
          - name: envoy-config
            mountPath: /etc/envoy

      volumes:
        - name: envoy-config
          configMap:
            name: envoy-config-app
---
apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app: app
    metrics: envoy
spec:
  selector:
    app: app
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: metrics
      port: 9901
      targetPort: 9901
