apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script
  namespace: default
data:
  init.sql: |
    USE quotesdb;

    CREATE TABLE IF NOT EXISTS quotes (
      id INT AUTO_INCREMENT PRIMARY KEY,
      text VARCHAR(255) NOT NULL,
      author VARCHAR(100)
    );

    INSERT INTO quotes (text, author) VALUES
      ('The only way to do great work is to love what you do.', 'Steve Jobs'),
      ('Innovation distinguishes between a leader and a follower.', 'Steve Jobs');
